local palette = require("glyphforged.palette")

return {
  {
    "EdenEast/nightfox.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      options = {
        transparent = false,
        terminal_colors = true,
        styles = {
          comments = "italic",
          keywords = "bold",
          types = "bold",
        },
      },
      palettes = {
        nightfox = {
          bg1 = palette.night,
          bg2 = palette.panel,
          bg3 = palette.panel,
          sel0 = palette.panel,
          sel1 = palette.violet,
          comment = palette.blue,
          black = palette.ink,
          red = palette.red,
          green = palette.green,
          yellow = palette.warning,
          blue = palette.blue,
          magenta = palette.violet,
          cyan = palette.cyan,
          white = palette.pearl,
          orange = palette.orange,
          pink = palette.pink,
        },
      },
      groups = {
        nightfox = {
          Normal = { fg = palette.pearl, bg = palette.night },
          NormalNC = { fg = palette.pearl, bg = palette.night },
          NormalFloat = { fg = palette.pearl, bg = palette.panel },
          FloatBorder = { fg = palette.cyan, bg = palette.panel },
          FloatTitle = { fg = palette.magenta, bg = palette.panel, style = "bold" },
          CursorLine = { bg = palette.panel },
          CursorColumn = { bg = palette.panel },
          ColorColumn = { bg = palette.panel },
          Cursor = { fg = palette.ink, bg = palette.cyan },
          Visual = { bg = palette.violet, fg = palette.ink, style = "bold" },
          Search = { fg = palette.ink, bg = palette.cyan, style = "bold" },
          IncSearch = { fg = palette.ink, bg = palette.magenta, style = "bold" },
          MatchParen = { fg = palette.ink, bg = palette.warning, style = "bold" },
          LineNr = { fg = palette.blue },
          CursorLineNr = { fg = palette.cyan, style = "bold" },
          SignColumn = { fg = palette.blue, bg = palette.night },
          FoldColumn = { fg = palette.violet, bg = palette.night },
          Folded = { fg = palette.blue, bg = palette.panel },
          WinSeparator = { fg = palette.violet, bg = palette.night },
          StatusLine = { fg = palette.pearl, bg = palette.panel },
          StatusLineNC = { fg = palette.blue, bg = palette.panel },
          TabLine = { fg = palette.blue, bg = palette.panel },
          TabLineSel = { fg = palette.ink, bg = palette.cyan, style = "bold" },
          TabLineFill = { bg = palette.night },
          Pmenu = { fg = palette.pearl, bg = palette.panel },
          PmenuSel = { fg = palette.ink, bg = palette.violet, style = "bold" },
          PmenuSbar = { bg = palette.panel },
          PmenuThumb = { bg = palette.magenta },
          DiagnosticError = { fg = palette.red },
          DiagnosticWarn = { fg = palette.warning },
          DiagnosticInfo = { fg = palette.blue },
          DiagnosticHint = { fg = palette.cyan },
          DiagnosticVirtualTextError = { fg = palette.red, bg = palette.panel },
          DiagnosticVirtualTextWarn = { fg = palette.warning, bg = palette.panel },
          DiagnosticVirtualTextInfo = { fg = palette.blue, bg = palette.panel },
          DiagnosticVirtualTextHint = { fg = palette.cyan, bg = palette.panel },
          GitSignsAdd = { fg = palette.green },
          GitSignsChange = { fg = palette.blue },
          GitSignsDelete = { fg = palette.red },
          TelescopeBorder = { fg = palette.cyan, bg = palette.panel },
          TelescopePromptBorder = { fg = palette.violet, bg = palette.panel },
          TelescopeResultsBorder = { fg = palette.blue, bg = palette.panel },
          TelescopePreviewBorder = { fg = palette.violet, bg = palette.panel },
        },
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "nightfox",
    },
  },
}
